apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: mvel1603/configserver:spring-cloud-bus-monitor-java-21
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: cashoperations-microservices-configmap
                  key: RABBITMQ_APPLICATION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071          # Port exposed to the outside world
      targetPort: 8071    # Internal pod port inside the k8s network. Must match the containerPort on line 21.