spring:
  application:
    name: cashoperations
  datasource:
    url: jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=3;TRACE_LEVEL_FILE=3
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  output:
    ansi:
      enabled: ALWAYS
fib:
  auth:
    api-key: f9Uie8nNf112hx8s

# SQL Query Logging Configuration
logging:
  level:
    # Hibernate SQL logging
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

    # Spring Data JPA logging
    org.springframework.data.jpa.repository: DEBUG
    org.springframework.orm.jpa: DEBUG

    # Transaction logging
    org.springframework.transaction: DEBUG

    # DataSource logging
    org.springframework.jdbc.core: DEBUG

    com.h2database: DEBUG  # This might catch some H2 internal logs
  file:
    name: /dev/stdout  # Force all logs to stdout
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"