build:
  version: "4.0"

cashreportingservice:
  message: "Welcome to Cash Reporting Service related PROD APIs "
  contactDetails:
    name: "Alex Smith - Product Owner"
    email: "asmith@example.com"
  onCallSupport:
    - (359) 423-3125
    - (359) 318-2314