services:
  network-deploy-service:
    networks:
      - cashoperations-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cashreportingservice-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      cashoperations:
        condition: service_healthy
    environment:
      CASHOPERATIONS_SERVICE_BASE_URL: cashoperations:http://cashoperations:8080/

  cashdocumentsservice-config:
    extends:
      service: cashreportingservice-config
    depends_on:
      cashreportingservice:
        condition: service_healthy
    environment:
      CASHREPORTINGSERVICE_SERVICE_BASE_URL: cashreportingservice:http://cashreportingservice:8081/cashreportingservice/