spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        #native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///C://Users//Admin//Desktop//Wichtiges//Tasks Interviews//FiBank//cashoperations//cashoperations-microservices//configserver//src//main//resources//config"
        git:
          uri: "https://github.com/metodi-velev/cashoperations-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

# encrypt: POST request to http://localhost:8071/encrypt
#           with the value to be encrypted as text body
# decrypt: POST request to http://localhost:8071/decrypt
#           with the value to be decrypted as text body

server:
  port: 8071
